config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/match', to: 'welcome#match', as: 'match'
  get '/signup', to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions, only: [:new, :create]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :groups, only: [:new, :create, :show, :update, :edit]
  resources :invitations, only: [:update, :destroy, :create]
  resources :memberships, only: :update
  resources :site_admins, only: :show
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :memberships
  has_many :groups, through: :memberships
  has_one :site_admin

  has_secure_password

  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :password, length: { minimum: 6 }, on: :create
  validates :bio, length: { maximum: 1000 }
  validate :valid_birthday

  def valid_birthday
    return if !birthdate
    valid_date = (Date.today.year - birthdate.year) < 112
    errors.add(:birthdate, 'must be valid') if !valid_date
  end

  def open_invitations
    Invitation.where('email = ? AND membership_status = ?', self.email, 'pending')
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def site_admin?
    !site_admin.nil?
  end

  def age
    (Time.new.to_date - self.birthdate.to_date).to_i / 365
  end

  # CLASS ANALYTICS

  def self.average_user_age
    users_with_bdays = self.where('birthdate IS NOT NULL').select('birthdate')
    "%.2f" % (users_with_bdays.inject(0) { |sum, user| sum + user.age } / users_with_bdays.size)
  end

  def self.user_state_count
    self.where('state IS NOT NULL AND state != ?', "").group('state').count('state')
  end

  def self.user_country_count
    self.where('country IS NOT NULL AND country != ?', "").group('country').count('country')
  end

  # INSTANCE ANALYTICS

  def total_gifts_received
    Membership.where("receiver_id = ?", self.id).count(:receiver_id)
  end

  def total_gifts_given
    Membership.where("user_id = ? AND receiver_id IS NOT NULL", self.id).count(:receiver_id)
  end

  def gifts_given_to
    Membership.where("user_id = ? AND receiver_id IS NOT NULL", self.id).collect(&:receiver_name)
  end

  def gifts_received_from
    Membership.where("receiver_id = ?", self.id).collect { |membership| membership.user.full_name }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized?
  before_action :find_user, only: [:show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      UserMailer.welcome_email(@user).deliver_now
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @total_gifts_received = current_user.total_gifts_received
    @total_gifts_given = current_user.total_gifts_given
    @gifts_given_to = current_user.gifts_given_to
    @gifts_received_from = current_user.gifts_received_from
  end

  def edit
    if @user == current_user
      render :edit
    else
      flash[:notice] = 'You do not have access to edit this profile.'
      redirect_to @user
    end
  end

  def update
    @user.update(user_params) ? (redirect_to @user) : (render :edit)
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name, :last_name, :email, :city, :state, :country,
      :birthdate, :bio, :password, :password_confirmation
    )
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/views/users/edit.html.erb
<div class="section">
  <div class="container">
    <div class="row">
      <div class="form-group col-md-8 col-md-offset-2 pushdown">
        <h3>Edit Profile</h3>
      </div>

      <%= form_for @user do |f| %>
        <div class="form-group col-md-8 col-md-offset-2">
          <% if @user.errors.any? %>
            <div id='error explanation'>
              <% @user.errors.full_messages.each do |msg| %>
                <div class="alert alert-danger" role="alert"><%= msg %></div>
              <% end %>
            </div>
          <% end %>
        </div>

        <div class="form-group col-md-8 col-md-offset-2">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, class: 'form-control' %>
        </div>

        <div class="form-group col-md-8 col-md-offset-2">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, class: 'form-control' %>
        </div>

        <div class="form-group col-md-8 col-md-offset-2">
          <%= f.label :birthdate %>
          <%= f.date_field :birthdate, class: 'form-control' %>
        </div>

        <div class="form-group col-md-8 col-md-offset-2">
          <%= f.label :city %>
          <%= f.text_field :city, class: 'form-control' %>
        </div>

        <div class="form-group col-md-8 col-md-offset-2">
          <%= f.label :state %>
          <%= f.collection_select :state, State.all, :name, :name %>
          <%= f.label :country %>
          <%= f.collection_select :country, Country.all, :name, :name, selected: 'United States of America' %>
        </div>

        <div class="form-group col-md-8 col-md-offset-2">
          <%= f.label "Bio" %>
          <%= f.text_area :bio, placeholder: "Help other gifters know you better (for example, what's your favorite color? shirt size? favorite foods? etc...)", class: 'form-control' %>
        </div>

        <div class="form-group col-md-8 col-md-offset-2">
          <%= f.submit "Update Profile", class: 'btn btn-danger' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-2 col-md-8 pushdown">
        <div class="form-group col-md-8 col-md-offset-2">
          <% if @user.errors.any? %>
            <% @user.errors.full_messages.each do |msg| %>
              <div class="alert alert-danger"><%= msg %></div>
            <% end %>
          <% end %>
        </div>

        <%= form_for @user, class: 'form-horizontal' do |f| %>
          <div class="form-group col-md-8 col-md-offset-2">
            <h2>Sign Up</h2>
          </div>
          <div class="form-group col-md-8 col-md-offset-2">
            <%= f.label :first_name, 'First Name' %>
            <%= f.text_field :first_name, placeholder: 'Jeff', class: 'form-control' %>
          </div>

          <div class="form-group col-md-8 col-md-offset-2">
            <%= f.label :last_name, 'Last Name' %>
            <%= f.text_field :last_name, placeholder: 'Katz', class: 'form-control' %>
          </div>

          <div class="form-group col-md-8 col-md-offset-2">
            <%= f.label :email %>
            <%= f.text_field :email, placeholder: 'jeff@example.com', class: 'form-control' %>
          </div>

          <div class="form-group col-md-8 col-md-offset-2">
            <%= f.label :password %>
            <%= f.password_field :password, placeholder: 'Password', class: 'form-control' %>
          </div>

          <div class="form-group col-md-8 col-md-offset-2">
            <%= f.label :password_confirmation, 'Confirm Password' %>
            <%= f.password_field :password_confirmation, placeholder: 'Confirm Password', class: 'form-control' %>
          </div>

          <div class="form-group col-md-8 col-md-offset-2">
            <%= f.submit 'Register', class: 'btn btn-danger' %>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-2 col-md-8 pushdown">
        <% if flash[:notice] %>
          <div class="alert alert-danger" role="alert"><%= flash[:notice] %></div>
        <% end %>
        <div>
          <div>
            <%= image_tag gravatar_url(@user, 150) %>
          </div>
          <div class="user-info">
            <div class='username section-title'><%= @user.full_name %></div>

            <div>
              <span class='user-data-header section-title'>City:</span>
              <div class='user-data'><%= @user.city %></div>
            </div>

            <div>
              <span class='user-data-header section-title'>State:</span>
              <div class='user-data'><%= @user.state %></div>
            </div>

            <div>
              <span class='user-data-header section-title'>Country:</span>
              <div class='user-data'><%= @user.country %></div>
            </div>

            <div>
              <span class='user-data-header section-title'>Birthdate:</span>
              <div class='user-data'><%= @user.birthdate.strftime("%m/%d/%Y") if @user.birthdate %></div>
            </div>

            <div>
              <span class='user-data-header section-title'>Bio:</span>
              <p class='user-data bio'><%= @user.bio %></p>
            </div>
          </div>
        </div><hr>

        <div>
          <div class='profile-section section-title'>My Gift Exchanges</div><hr>
          <% if @user.groups.any? %>
            <table class="table">
              <thead>
                <tr>
                <th>Group Name</th>
                </tr>
              </thead>
              <tbody>
                <% @user.groups.each do |group| %>
                  <tr>
                    <td><%= link_to group.name, group_path(group) %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% else %>
            You are not in any gift exchanges.
          <% end %>
        </div>

        <div>
          <div class='profile-section section-title'>My Invitations</div><hr>
          <% if @user.open_invitations.any? %>
            <table class="table">
              <thead>
                <tr>
                  <th>Group Name</th>
                </tr>
              </thead>
              <tbody>
                <% @user.open_invitations.each do |invitation| %>
                  <% if invitation.group.open %>
                    <tr>
                      <td><%= invitation.group.name %></td>
                      <td><%= link_to 'Accept', invitation_path(invitation), method: :patch, class:'btn btn-success btn-sm' %></td>
                      <td><%= link_to 'Decline', invitation_path(invitation), method: :delete, class:'btn btn-danger btn-sm'  %></td>
                  </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          <% else %>
            You do not have any open invitations.
          <% end %>
        </div>

        <div>
          <div class='profile-section section-title'>User Gift Exchange Information</div><hr>
          <table class="table">
            <thead>
              <tr>
                <th>Total Gifts Received</th>
                <th>Total Gifts Given</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= @total_gifts_received %></td>
                <td><%= @total_gifts_given %></td>
              </tr>
            </tbody>
          </table>
        </div>

        <% unless @gifts_given_to.empty? || @gifts_received_from.empty? %>
          <div>
            <table class="table">
              <thead>
                <tr>
                  <th>Gifts Given To</th>
                </tr>
              </thead>
              <tbody>
                <% @gifts_given_to.each do |receiver| %>
                  <tr>
                    <td><%= receiver %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>

          <div>
            <table class="table">
              <thead>
                <tr>
                  <th>Gifts Received From</th>
                </tr>
              </thead>
              <tbody>
                <% @gifts_received_from.each do |giver| %>
                  <tr>
                    <td><%= giver %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>