config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/match', to: 'welcome#match', as: 'match'
  get '/signup', to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions, only: [:new, :create]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :groups, only: [:new, :create, :show, :update, :edit]
  resources :invitations, only: [:update, :destroy, :create]
  resources :memberships, only: :update
  resources :site_admins, only: :show
end

app/views/shared/_admin_controls.html.erb
<%= (link_to "Match", membership_path(@group), method: :patch, class: 'btn btn-danger') if @group.open%>
<%= link_to "Edit Group Info", edit_group_path, method: :get, class: 'btn btn-danger' %>
<% if @group.open %>
<%= form_tag '/invitations', method: :post, class: 'form-horizontal' do %>
  <p>
    <div class="form-group col-md-12">
      <%= label_tag :invitations, 'Invite More Friends' %><br/>
      <%= text_area_tag :invitations, nil, placeholder: 'Please enter comma separated email addresses of friends you would like to invite to this group (jkatz@example.com, icandy@example.com, etc.).', class: 'form-control' %>
      <%= hidden_field_tag 'id', @group.id %>
    </div>
  </p>
  
  <p>
    <div class="form-group col-md-12">
      <%= submit_tag 'Send More Invites', class: 'btn btn-danger' %>
    </div>
  </p>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="section section-secondary">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <h1>GiftSwap</h1>
        <p>
          GiftSwap is a Secret Santa Gift Exchane generator that assigns unique matches to members in a gift exchange. GiftSwap is a project built by <a class="footer-links" href="https://www.linkedin.com/in/patelsagar">Sagar Patel</a>, <a class="footer-links" href="https://www.linkedin.com/in/justincurhan">Justin Curhan</a> and <a class="footer-links" href="https://www.linkedin.com/in/leonharary">Leon Harary</a> who are students of The Flatiron School.
        </p>
        <p>
          <% if logged_in? %>
            <%= link_to 'Site Administrator', site_admin_path(current_user) %>
          <% end %>
        </p>
      </div>
      <div class="col-sm-6">
        <p class="text-info text-right">
          <br>
          <br>
        </p>
        <div class="row">
          <div class="col-md-12 hidden-xs text-right">
            <a href="https://github.com/sagarpatel8384/gift-exchange-app">
              <i class="fa fa-3x fa-fw fa-github text-inverse"></i>
            </a>
            <a href="https://github.com/lharary" target="_blank">
              <img src="<%= image_url('leon.jpg') %>" class="center-block img-circle img-responsive profile-pic">
            </a>
            <a href="https://github.com/sagarpatel8384" target="_blank">
              <img src="<%= image_url('sagar.jpg') %>" class="center-block img-circle img-responsive profile-pic">
            </a>
            <a href="https://github.com/jcurhan" target="_blank">
              <img src="<%= image_url('justin.jpg') %>" class="center-block img-circle img-responsive profile-pic">
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>">GiftSwap</a>
    </div>

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Group +", new_group_path %></li>
          <li class="dropdown"><!-- If logged in -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= image_tag gravatar_url(current_user, 24) %>
              <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
              <li><%= link_to "Log Out", logout_path %></li>
            </ul>
           </li>
        <% else %>
          <li><%= link_to "Sign Up", signup_path %></li>
          <li><%= link_to "Log In", login_path %></li> <!-- If logged out -->
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_homepage_results.html.erb
<h3>Here are your gift exchange matches!</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Gift Giver</th>
      <th>Gift Receiver</th>
    </tr>
  </thead>
  <tbody>
    <% @results.each do | giver, receiver| %>
      <tr>
        <td><%= giver %></td>
        <td><%= receiver %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_match_results.html.erb
<h3>Here are your GiftSwap matches!</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Gift Giver</th>
      <th>Gift Receiver</th>
    </tr>
  </thead>
  <tbody>
    <% @results.each do | giver, receiver| %>
      <tr>
        <td><%= giver %></td>
        <td><%= receiver %></td>
      </tr>
    <% end %>
  </tbody>
</table>