config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/match', to: 'welcome#match', as: 'match'
  get '/signup', to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions, only: [:new, :create]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :groups, only: [:new, :create, :show, :update, :edit]
  resources :invitations, only: [:update, :destroy, :create]
  resources :memberships, only: :update
  resources :site_admins, only: :show
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authorized?
  layout 'index'

  def index
    if logged_in?
      redirect_to user_path(current_user)
    end
  end

  def match
    names = params[:users]
    results = match_pairs(names)
    match_string = Parser.build_html(results)
    render json: {htmlString: match_string}
  end
end

app/views/welcome/index.html.erb
<div class="cover">
  <!-- GITHUB BADGE -->
  <a href="https://github.com/sagarpatel8384/gift-exchange-app"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://camo.githubusercontent.com/365986a132ccd6a44c23a9169022c0b5c890c387/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f7265645f6161303030302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png"></a>
  <!-- NAV -->
  <div class="navbar homepage-nav">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="<%= root_path %>"><span>GiftSwap</span></a>
      </div>
      <div class="collapse navbar-collapse" id="navbar-ex-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Sign Up", signup_path, class: "nav-links" %></li>
          <li><%= link_to "Log In", login_path, class: "nav-links nav-link-login" %></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- COVER -->
  <div class="cover-image"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1 class="text-inverse">Gift Giving Made Easy</h1>
        <p class="text-inverse">Start a Secret Santa Gift Exchange Today</p>
        <br>
        <br>
        <button type="button" class="btn btn-lg btn-danger btn-size" data-toggle="modal" data-target="#myModal">Try</button>
        <%= link_to 'Sign Up', new_user_path, class: "btn btn-lg btn-success btn-size" %>
      </div>
    </div>
  </div>
</div>

<!-- MODAL -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Enter the names for your GiftSwap.</h4>
      </div>
      <div class="modal-body">
        <div id="full-width-head">
          <%= form_tag root_path, method: 'get', class: 'form-horizontal', id: 'match-form' do %>
            <div class='form-group'>
              <div class="col-md-6">
                <%= text_field_tag "emails[]", nil, class: 'form-control', placeholder: 'Name', placeholder: 'Name' %>
              </div>
              <div class="col-md-6">
                <%= text_field_tag "emails[]", nil, class: 'form-control', placeholder: 'Name' %>
              </div>
            </div>

            <div class='form-group'>
              <div class="col-md-6">
                <%= text_field_tag "emails[]", nil, class: 'form-control', placeholder: 'Name' %>
              </div>
              <div class="col-md-6">
                <%= text_field_tag "emails[]", nil, class: 'form-control', placeholder: 'Name' %>
              </div>
            </div>

            <div class='form-group'>
              <div class="col-md-6">
                <%= text_field_tag "emails[]", nil, class: 'form-control', placeholder: 'Name' %>
              </div>
              <div class="col-md-6">
                <%= text_field_tag "emails[]", nil, class: 'form-control', placeholder: 'Name' %>
              </div>
            </div>

            <div class='form-group'>
              <div class="col-md-6">
                <%= text_field_tag "emails[]", nil, class: 'form-control', placeholder: 'Name' %>
              </div>
              <div class="col-md-6">
                <%= text_field_tag "emails[]", nil, class: 'form-control', placeholder: 'Name' %>
              </div>
            </div>

            <div class='form-group'>
              <div class="col-md-6">
                <%= text_field_tag "emails[]", nil, class: 'form-control', placeholder: 'Name' %>
              </div>
              <div class="col-md-6">
                <%= text_field_tag "emails[]", nil, class: 'form-control', placeholder: 'Name' %>
              </div>
            </div>

            <div class='form-group'>
              <div class="col-md-6">
                <%= submit_tag 'Draw Names', class: 'btn btn-danger', id: 'match-names' %>
                <%= link_to 'Add More Names', signup_path, class: 'btn btn-success' %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>